### ISSUE TITLE
Added all contributers name and project admin name in the README.md and upadte README.md and also add strangers graph

### ISSUE THREAD

**Issue by Ayush7614** [IIITM-Jay/Property-management-System-Django-Full-Stack-#40]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**]
![screenshot-github com-2021 02 07-22_11_43](https://user-images.githubusercontent.com/67006255/107153115-d6cf0d00-6991-11eb-8bf5-aa0d555dff2c.png)

**Comment by Ayush7614** [comment]
Assigne me this issue under DWOC

**Comment by IIITM-Jay** [comment]
@Ayush7614 Aysuh is your feature automatic ... the same issue is already opened #37 , but my question is can you able to add automation in the same...

**Comment by Ayush7614** [comment]
Can you give example for this like what thing you have talking about

**Comment by IIITM-Jay** [comment]
@Ayush7614 First of all introduce yourself a little bit of yours so that I can know about you more...
Coming on to your opened issue ... have you checked #37 ...
The work you have mentioned requires manual updation of the contributors table but I want that after successfully merging of the respective PRs by new comers it got automatically added to the contributors list

**Comment by IIITM-Jay** [comment]
@Ayush7614 also Aayush, see the title of the issue you have mentioned its **strangers** or **stargazers** :laughing: :rofl: 
be careful while writing anything and give some time to understand the underlying concepts and then move further.
